version: '3'

networks:
  laravel:
services:
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
      - type: bind
        source: ./
        target: /workspace
    networks:
      - laravel

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

#  composer:
#    build:
#      context: ./dockerfiles
#      dockerfile: php.dockerfile
#      args:
#        - UID=${UID:-1000}
#        - GID=${GID:-1000}
#    volumes:
#      - ./src:/var/www/html
#    depends_on:
#      - php
#    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
#    networks:
#      - laravel
